steps:
  # Build Backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/unilink-agent-api", "."]

  # Push images
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/unilink-agent-api"]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "unilink-agent-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/unilink-agent-api"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/unilink-agent-api"

# Add logging configuration
options:
  logging: CLOUD_LOGGING_ONLY
