big_tech = [
    "Google",
    "Apple",
    "Meta",
    "Amazon",
    "Microsoft",
    "Netflix",
]

quant = [
    "3Red Partners",
    "A Priori Investments",
    "Acadian Asset Management",
    "Akuna Capital",
    "Albatross Labs",
    "AlphaGrep",
    "AlphaSimplex",
    "Alphataraxia Management",
    "Alyeska Investment Group",
    "Ansatz Capital",
    "AQR Capital Management",
    "Aquatic Capital",
    "Arrowstreet Capital",
    "ART Advisors",
    "Aspect Capital",
    "AXQ Capital",
    "Balyasny Asset Management",
    "Banyan Alpha Investment",
    "Belvedere Trading",
    "BlackEdge Capital",
    "Bluefin Capital Management",
    "Blueshift Asset Management",
    "Boerboel Trading",
    "Boulder Hill Capital Management",
    "Brevan Howard",
    "Bridgewater Associates",
    "Cantor Fitzgerald",
    "Capital Fund Management",
    "Capital Markets Trading",
    "Capstone",
    "Capula",
    "Caxton Associates",
    "Centiva Capital",
    "Chicago Trading Company",
    "Citadel",
    "Consolidated Trading",
    "CQS",
    "Cubist (part of Point72)",
    "Dark Forest",
    "DE Shaw",
    "Dolat Capital",
    "DRW",
    "Duality Group",
    "DV Trading",
    "Edgehog Trading",
    "Edgestream Partners",
    "Eisler Capital",
    "Elk Capital Markets",
    "Elequin Capital",
    "Emergent Trading",
    "Engineers Gate",
    "Eqvilent",
    "Ergoteles Capital",
    "Eschaton Trading",
    "Evergreen Statistical Trading",
    "ExodusPoint",
    "Five Rings",
    "Florin Court Capital",
    "Flow Traders",
    "Freestone Grove Partners",
    "G-Research",
    "GAM Systematic",
    "Garda Capital Partners",
    "Gelber Group",
    "Geneva Trading",
    "Geode Capital Management",
    "Graham Capital Management",
    "Graviton Research Capital",
    "Group One Trading",
    "GSA Capital Partners",
    "GTS",
    "HAP Capital",
    "Headlands Technologies",
    "Hudson Bay Capital",
    "Hudson River Trading",
    "IMC Financial Markets",
    "Jacobs Levy Equity Management",
    "Jain Global",
    "Jane Street",
    "Jocassee Quantitative",
    "Jump Trading",
    "Kepos Capital",
    "Kore Trading",
    "Kula Investments",
    "Laurion Capital Management",
    "Lord Abbett",
    "Lynx Asset Management",
    "Mako",
    "Man Group",
    "Mana Partners",
    "Marquette Partners",
    "Marshall Wace",
    "Maven Securities",
    "Millburn",
    "Monoceros",
    "Nebula Research & Development",
    "Old Mission Capital",
    "Optiver",
    "Paloma Partners",
    "PanAgora",
    "Parallax Volatility Advisers",
    "PDT Partners",
    "PEAK6",
    "PGIM Quant Solutions",
    "Prime Trading",
    "QMS Capital Management",
    "Qsemble Capital Management",
    "Quadeye",
    "Quadrature",
    "Quantbot Technologies",
    "Quantbox Research",
    "Quantitative Investment Management",
    "Quantlab Financial",
    "Quantumrock Capital",
    "Qube Research & Technologies",
    "QVR Advisors",
    "Radix Trading",
    "Renaissance Technologies",
    "Rokos Capital Management",
    "Rosetta Analytics",
    "RSJ",
    "Schonfeld Strategic Advisors",
    "Segantii Capital Management",
    "Sensato Investors",
    "Seven Eight Capital",
    "Spark Investment Management",
    "Squarepoint Capital",
    "Stevens Capital Management",
    "Summit Securities Group",
    "Sumo",
    "Sunrise Futures",
    "Susquehanna International Group, LLP (SIG)",
    "Systematica Investments",
    "Tanius Technology",
    "Teza Technologies",
    "TGS Management Company",
    "Tower Research Capital",
    "Tradebot",
    "Tradelink Holdings",
    "TransMarket Group",
    "Trexquant Investment",
    "Two Sigma",
    "Valkyrie Trading",
    "Vatic Investments",
    "Vector Trading",
    "Verition Fund Management",
    "Virtu Financial",
    "Volant Trading",
    "Voleon Group",
    "Voloridge Investment Management",
    "Volterra Technologies",
    "Walleye Capital",
    "WH Trading",
    "Wincent",
    "Winton Capital Management",
    "Wintermute",
    "Wolverine Trading",
    "WorldQuant (part of Millenium)",
    "Xantium (part of Tudor)",
    "XR Trading",
    "XTX Markets",
]

unicorns = [
    "ByteDance",
    "OpenAI",
    "Ant Group",
    "SpaceX",
    "Reliance Retail",
    "Shein",
    "Stripe",
    "Databricks",
    "Reliance Jio",
    "xAI",
    "Revolut",
    "Waymo",
    "Checkout.com",
    "JUUL",
    "Canva",
    "Fanatics",
    "Cruise",
    "Alibaba Bendi Shenghuo Fuwu Gongsi",
    "Chime",
    "CoreWeave",
    "Epic Games",
    "BYJU'S",
    "Envision Group",
    "J&T Express",
    "FNZ",
    "ChangXin Memory Technologies",
    "Anthropic",
    "JD Digits",
    "Miro",
    "Xiaohongshu",
    "Yuanfudao",
    "Trendyol Group",
    "Yinwang Smart Technology",
    "Discord",
    "Gopuff",
    "Rapyd",
    "Genki Forest",
    "CloudKitchens",
    "Bitmain",
    "GAC Aion New Energy Automobile",
    "Anduril Industries",
    "Scale AI",
    "Rippling",
    "Plaid",
    "OpenSea",
    "Grammarly",
    "Devoted Health",
    "Celonis",
    "Faire",
    "Figma",
    "Brex",
    "Infinite Reality",
    "PhonePe",
    "GoodLeap",
    "Biosplice Therapeutics",
    "Xingsheng Youxuan",
    "Wiz",
    "Deel",
    "Northvolt",
    "Airtable",
    "Dunamu",
    "The Access Group",
    "Notion",
    "Alchemy",
    "Colossal Biosciences",
    "KuCoin",
    "Digital Currency Group",
    "Ripple",
    "Zuoyebang",
    "Chehaoduo",
    "Talkdesk",
    "Thrasio",
    "Lalamove",
    "Mahindra Electric Automobile",
    "Gusto",
    "Navan",
    "Tata Passenger Electric Mobility",
    "N26",
    "Tanium",
    "Yanolja",
    "Perplexity",
    "VAST Data",
    "Niantic",
    "HeyTea",
    "Octopus Energy",
    "EV Co",
    "Ping An Healthcare Management",
    "Kavak",
    "Nuro",
    "Personio",
    "Bolt",
    "Tipalti",
    "The CrownX",
    "DJI",
    "Flexport",
    "Fireblocks",
    "THG Ingenuity",
    "FalconX",
    "StarkWare Industries",
    "Dream11",
    "Caris Life Sciences",
    "Hopin",
    "CALB",
    "AutoStore",
    "Ramp",
    "Circle",
    "Leapmotor",
    "Jiedaibao",
    "Dapper Labs",
    "Netskope",
    "Snyk",
    "Carta",
    "Kakao Japan",
    "Gong",
    "Blockchain.com",
    "ConsenSys",
    "Ro",
    "Meicai",
    "Constellation Automotive Group",
    "Attentive",
    "Cohesity",
    "The Boring Company",
    "NYDIG",
    "Impossible Foods",
    "Toss",
    "1Password",
    "Automation Anywhere",
    "WeDoctor",
    "Klarna",
    "Ola",
    "Ziroom",
    "Razorpay",
    "Snapdeal",
    "Mollie",
    "CRED",
    "Doctolib",
    "GTA Semiconductor",
    "DataRobot",
    "Upgrade",
    "Hinge Health",
    "Hello TransTech",
    "Benchling",
    "Mistral AI",
    "CMC",
    "Lianjia",
    "Changxin New Bridge",
    "iCapital Network",
    "Didi Woya",
    "Biocon Biologics",
    "Applied Intuition",
    "Commure",
    "Grafana Labs",
    "Animoca Brands",
    "Monzo",
    "Lyra Health",
    "Cityblock Health",
    "Workato",
    "Vice Media",
    "Back Market",
    "RELEX Solutions",
    "Postman",
    "Fivetran",
    "Contentsquare",
    "SandboxAQ",
    "SVOLT",
    "Mambu",
    "Airwallex",
    "Vuori",
    "Cohere",
    "Helion Energy",
    "Vinted",
    "Helsing",
    "Trade Republic",
    "Rappi",
    "Sierra Space",
    "Quantinuum",
    "Odoo",
    "Collibra",
    "Redwood Materials",
    "Xiaodu",
    "6sense",
    "Oura",
    "MTN Group Fintech",
    "Abnormal Security",
    "QuintoAndar",
    "SambaNova Systems",
    "Pine Labs",
    "United Imaging Healthcare",
    "C6 Bank",
    "Hopper",
    "OfBusiness",
    "Icertis",
    "VerSe Innovation",
    "Moon Active",
    "Zepz",
    "WeBank",
    "WeWork China",
    "Royole Corporation",
    "Cockroach Labs",
    "Lenskart",
    "PointClickCare",
    "ShareChat",
    "Coalition",
    "Zepto",
    "Safe Superintelligence",
    "DataDirect Networks",
    "Neuralink",
    "Whatnot",
    "Sunwoda Electric Vehicle Battery",
    "Mynt",
    "Reify Health",
    "Cerebral",
    "Creditas",
    "Chipone Technology",
    "Qonto",
    "BetterUp",
    "Binance.US",
    "Pleo",
    "Sonar",
    "Glean",
    "Checkr",
    "Color",
    "Lendable",
    "wefox",
    "iFood",
    "Hugging Face",
    "Sierra",
    "Tricentis",
    "Manner",
    "OneTrust",
    "Socure",
    "VIPKID",
    "Guild",
    "Alan",
    "Zhiji Auto",
    "Ruipeng Pet Healthcare",
    "Outreach",
    "Lightmatter",
    "OutSystems",
    "Sorare",
    "Arctic Wolf",
    "Voyah",
    "Kakao Mobility",
    "G-P/Globalization Partners",
    "ThoughtSpot",
    "dbt Labs",
    "Relativity Space",
    "Armis Security",
    "Zipline",
    "Hithium Energy Storage",
    "SSENSE",
    "Bitpanda",
    "Dataminr",
    "AngelList",
    "Weee!",
    "SumUp",
    "Wealthsimple",
    "Kraken",
    "Turing",
    "Cerebras Systems",
    "Branch",
    "Yuga Labs",
    "Houzz",
    "Next Insurance",
    "BrowserStack",
    "Clubhouse",
    "ClickUp",
    "Patreon",
    "MEGVII",
    "Aurora Solar",
    "Zapier",
    "Skims",
    "AlphaSense",
    "Radiology Partners",
    "Inflection AI",
    "Aptos",
    "Skydance Media",
    "The Brandtech Group",
    "Webflow",
    "Tekion",
    "insightsoftware",
    "Hozon",
    "Medlinker",
    "Farmers Business Network",
    "Yunwang Wandian",
    "StockX",
    "OYO",
    "Qontigo",
    "ENOVATE Motors",
    "Dutchie",
    "Articulate",
    "Avride",
    "Harness",
    "Dataiku",
    "Papaya Global",
    "Noom",
    "Goat Group",
    "o9 Solutions",
    "Upstox",
    "Relativity",
    "WHOOP",
    "SpotOn",
    "Learneo",
    "Aptean",
    "Ottobock",
    "Handshake",
    "Rec Room",
    "Flock Safety",
    "Chargebee",
    "Highspot",
    "Mirakl",
    "Via",
    "ApplyBoard",
    "Wonder",
    "Meesho",
    "Celestia",
    "Vultr",
    "Aledade",
    "Rokt",
    "Cribl",
    "Innovaccer",
    "Unacademy",
    "Baichuan Intelligence",
    "GoStudent",
    "MoonPay",
    "Hive Box",
    "HighRadius",
    "Market Kurly",
    "Starburst",
    "Youxia Motors",
    "Starling Bank",
    "Zhizi Automobile",
    "Uber Freight",
    "Moonshot AI",
]

top_5 = [
    "Princeton University",
    "Massachusetts Institute of Technology",
    "Harvard University",
    "Stanford University",
    "Yale University",
]

top_10 = [
    "Princeton University",
    "Massachusetts Institute of Technology",
    "Harvard University",
    "Stanford University",
    "Yale University",
    "California Institute of Technology",
    "Duke University",
    "Johns Hopkins University",
    "Northwestern University",
    "University of Pennsylvania",
]

top_20 = [
    "Princeton University",
    "Massachusetts Institute of Technology",
    "Harvard University",
    "Stanford University",
    "Yale University",
    "California Institute of Technology",
    "Duke University",
    "Johns Hopkins University",
    "Northwestern University",
    "University of Pennsylvania",
    "Cornell University",
    "University of Chicago",
    "Brown University",
    "Columbia University",
    "Dartmouth College",
    "University of California, Los Angeles",
    "University of California, Berkeley",
    "Rice University",
    "University of Notre Dame",
    "Vanderbilt University",
]

top_50 = [
    "Princeton University",
    "Massachusetts Institute of Technology",
    "Harvard University",
    "Stanford University",
    "Yale University",
    "California Institute of Technology",
    "Duke University",
    "Johns Hopkins University",
    "Northwestern University",
    "University of Pennsylvania",
    "Cornell University",
    "University of Chicago",
    "Brown University",
    "Columbia University",
    "Dartmouth College",
    "University of California, Los Angeles",
    "University of California, Berkeley",
    "Rice University",
    "University of Notre Dame",
    "Vanderbilt University",
    "Carnegie Mellon University",
    "University of Michigan",
    "Washington University in St. Louis",
    "Emory University",
    "Georgetown University",
    "University of Virginia",
    "University of North Carolina at Chapel Hill",
    "University of Southern California",
    "University of California, San Diego",
    "New York University",
    "University of Florida",
    "The University of Texas at Austin",
    "Georgia Institute of Technology",
    "University of California, Davis",
    "University of California, Irvine",
    "University of Illinois Urbana-Champaign",
    "Boston College",
    "Tufts University",
    "University of California, Santa Barbara",
    "University of Wisconsin-Madison",
    "Boston University",
    "The Ohio State University",
    "Rutgers University-New Brunswick",
    "University of Maryland, College Park",
    "University of Rochester",
    "Lehigh University",
    "Purdue University",
    "University of Georgia",
    "University of Washington",
    "Wake Forest University",
]
